# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      ES_HOST: ${{ secrets.ES_HOST }}
      ES_PORT: ${{ secrets.ES_PORT }}
      ES_USERNAME: ${{ secrets.ES_USERNAME }}
      ES_PASSWORD: ${{ secrets.ES_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9.19
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.19"

      - name: Create .env file from GitHub Secrets
        run: |
          echo "ES_HOST=${{ secrets.ES_HOST }}" >> .env
          echo "ES_PORT=${{ secrets.ES_PORT }}" >> .env
          echo "ES_USERNAME=${{ secrets.ES_USERNAME }}" >> .env
          echo "ES_PASSWORD=${{ secrets.ES_PASSWORD }}" >> .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # To add.
      - name: Test with pytest
        run: |
          pytest
